import type { CameraParameterProfile, NarrativePurpose } from './types';

export const CAMERA_PARAMETER_PROFILES: Record<NarrativePurpose, CameraParameterProfile> = {
  emphasis: {
    id: 'emphasis',
    title: 'Emphasis profile',
    reason:
      'Emphasis uses a tighter frame, mild zoom-in bias, and stronger view changes to keep attention on the selected target.',
    timing: {
      durationMs: 3000,
      stayMs: 1500,
      interpolationType: 'none',
      interpolationDurationMs: 0,
      pathDurationPerKmMs: 8,
      maxDurationMs: 12000,
      speedTier: 0.45,
    },
    framing: {
      paddingRatio: 0.16,
      contextPaddingRatio: 0.24,
      minPaddingPx: 48,
      maxPaddingRatio: 0.26,
      zoomBias: 0.05,
      contextZoomOut: 1.2,
      pitchRange: [30, 62],
      bearingDelta: 28,
    },
    adaptation: {
      densityPaddingScale: 0.1,
      densityZoomOutScale: 0.45,
      elevationZoomOutScale: 0.9,
      elevationPitchScale: 0.6,
      largeAreaPaddingScale: 0.04,
      largeAreaZoomOutScale: 0.35,
      regionPaddingBonus: 0.02,
      multiplePaddingBonus: 0.04,
      pathPaddingBonus: 0.03,
      rotationPaddingBonus: 0.05,
      maxAdaptiveZoomOut: 1.15,
      overflowZoomOutScale: 3.5,
    },
    targetPolicy: {
      requiresTarget: true,
      requiresComparison: false,
    },
  },
  overview: {
    id: 'overview',
    title: 'Overview profile',
    reason:
      'Overview uses wider framing and a slight zoom-out bias so the selected context remains visible as a whole.',
    timing: {
      durationMs: 5000,
      stayMs: 1000,
      interpolationType: 'none',
      interpolationDurationMs: 0,
      pathDurationPerKmMs: 10,
      maxDurationMs: 14000,
      speedTier: 0.35,
    },
    framing: {
      paddingRatio: 0.2,
      contextPaddingRatio: 0.26,
      minPaddingPx: 48,
      maxPaddingRatio: 0.3,
      zoomBias: -0.12,
      contextZoomOut: 1.35,
      pitchRange: [25, 58],
      bearingDelta: 24,
    },
    adaptation: {
      densityPaddingScale: 0.1,
      densityZoomOutScale: 0.55,
      elevationZoomOutScale: 0.65,
      elevationPitchScale: 0.55,
      largeAreaPaddingScale: 0.06,
      largeAreaZoomOutScale: 0.45,
      regionPaddingBonus: 0.04,
      multiplePaddingBonus: 0.06,
      pathPaddingBonus: 0.04,
      rotationPaddingBonus: 0.06,
      maxAdaptiveZoomOut: 1.25,
      overflowZoomOutScale: 3,
    },
    targetPolicy: {
      requiresTarget: true,
      requiresComparison: false,
    },
  },
  comparison: {
    id: 'comparison',
    title: 'Comparison profile',
    reason:
      'Comparison uses the widest shared view and conservative pitch changes so multiple targets can be read together.',
    timing: {
      durationMs: 3500,
      stayMs: 3000,
      interpolationType: 'none',
      interpolationDurationMs: 0,
      pathDurationPerKmMs: 9,
      maxDurationMs: 14000,
      speedTier: 0.4,
    },
    framing: {
      paddingRatio: 0.24,
      contextPaddingRatio: 0.3,
      minPaddingPx: 56,
      maxPaddingRatio: 0.34,
      zoomBias: -0.25,
      contextZoomOut: 1.5,
      pitchRange: [20, 50],
      bearingDelta: 18,
    },
    adaptation: {
      densityPaddingScale: 0.12,
      densityZoomOutScale: 0.65,
      elevationZoomOutScale: 0.5,
      elevationPitchScale: 0.4,
      largeAreaPaddingScale: 0.08,
      largeAreaZoomOutScale: 0.55,
      regionPaddingBonus: 0.05,
      multiplePaddingBonus: 0.08,
      pathPaddingBonus: 0.04,
      rotationPaddingBonus: 0.05,
      maxAdaptiveZoomOut: 1.4,
      overflowZoomOutScale: 2.5,
    },
    targetPolicy: {
      requiresTarget: true,
      requiresComparison: true,
    },
  },
  supplement: {
    id: 'supplement',
    title: 'Supplement profile',
    reason:
      'Supplement reserves more negative screen-space offset and padding so annotations or context can sit beside the target.',
    timing: {
      durationMs: 3500,
      stayMs: 1500,
      interpolationType: 'none',
      interpolationDurationMs: 0,
      pathDurationPerKmMs: 8,
      maxDurationMs: 12000,
      speedTier: 0.4,
    },
    framing: {
      paddingRatio: 0.24,
      contextPaddingRatio: 0.3,
      minPaddingPx: 56,
      maxPaddingRatio: 0.32,
      zoomBias: -0.05,
      contextZoomOut: 1.35,
      pitchRange: [25, 58],
      bearingDelta: 22,
      offsetRatio: [-0.14, 0],
    },
    adaptation: {
      densityPaddingScale: 0.1,
      densityZoomOutScale: 0.5,
      elevationZoomOutScale: 0.6,
      elevationPitchScale: 0.5,
      largeAreaPaddingScale: 0.06,
      largeAreaZoomOutScale: 0.45,
      regionPaddingBonus: 0.04,
      multiplePaddingBonus: 0.06,
      pathPaddingBonus: 0.04,
      rotationPaddingBonus: 0.06,
      maxAdaptiveZoomOut: 1.25,
      overflowZoomOutScale: 3,
    },
    targetPolicy: {
      requiresTarget: true,
      requiresComparison: false,
    },
  },
  dynamic: {
    id: 'dynamic',
    title: 'Dynamic profile',
    reason: 'Dynamic cameras animate the current view without requiring a geographic target.',
    timing: {
      durationMs: 10000,
      stayMs: 0,
      interpolationType: 'none',
      interpolationDurationMs: 0,
      maxDurationMs: 12000,
    },
    framing: {
      paddingRatio: 0.14,
      contextPaddingRatio: 0.2,
      minPaddingPx: 48,
      maxPaddingRatio: 0.24,
      zoomBias: 0,
      contextZoomOut: 1,
      pitchRange: [25, 55],
      bearingDelta: 20,
    },
    adaptation: {
      densityPaddingScale: 0,
      densityZoomOutScale: 0,
      elevationZoomOutScale: 0,
      elevationPitchScale: 0.35,
      largeAreaPaddingScale: 0,
      largeAreaZoomOutScale: 0,
      regionPaddingBonus: 0,
      multiplePaddingBonus: 0,
      pathPaddingBonus: 0,
      rotationPaddingBonus: 0,
      maxAdaptiveZoomOut: 0,
      overflowZoomOutScale: 0,
    },
    targetPolicy: {
      requiresTarget: false,
      requiresComparison: false,
    },
  },
  basic: {
    id: 'basic',
    title: 'Manual/basic profile',
    reason: 'Manual cameras keep the current view as the starting point and only apply the selected shot defaults.',
    timing: {
      durationMs: 3000,
      stayMs: 0,
      interpolationType: 'none',
      interpolationDurationMs: 0,
      pathDurationPerKmMs: 8,
      maxDurationMs: 12000,
      speedTier: 0.5,
    },
    framing: {
      paddingRatio: 0.14,
      contextPaddingRatio: 0.22,
      minPaddingPx: 48,
      maxPaddingRatio: 0.26,
      zoomBias: 0,
      contextZoomOut: 1,
      pitchRange: [20, 60],
      bearingDelta: 24,
    },
    adaptation: {
      densityPaddingScale: 0.05,
      densityZoomOutScale: 0.25,
      elevationZoomOutScale: 0.35,
      elevationPitchScale: 0.45,
      largeAreaPaddingScale: 0.04,
      largeAreaZoomOutScale: 0.3,
      regionPaddingBonus: 0.02,
      multiplePaddingBonus: 0.04,
      pathPaddingBonus: 0.03,
      rotationPaddingBonus: 0.04,
      maxAdaptiveZoomOut: 0.8,
      overflowZoomOutScale: 2,
    },
    targetPolicy: {
      requiresTarget: false,
      requiresComparison: false,
    },
  },
};

export function getCameraParameterProfile(purpose: NarrativePurpose) {
  return CAMERA_PARAMETER_PROFILES[purpose] ?? CAMERA_PARAMETER_PROFILES.basic;
}
